version: "3.8"

services:
  subscriptionbff:
    build: subscriptionbff-service
    mem_limit: 512m
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: '512m'
      restart_policy:
        condition: on-failure
    networks:
      - app-tier
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
  subscriptionapi:
    build: subscriptionapi-service
    mem_limit: 512m
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: '512m'
      restart_policy:
        condition: on-failure
    networks:
      - app-tier
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
  mailer:
    build: mailer-service
    mem_limit: 512m
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: '512m'
      restart_policy:
        condition: on-failure
    networks:
      - app-tier
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
    depends_on:
      rabbitmq:
        condition: service_healthy
  eureka:
    build: service-registry
    mem_limit: 512m
    environment:
      eureka.instance.hostname: eureka
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
    networks:
      - app-tier
  mysql:
    image: mysql:5.7.32
    mem_limit: 512m
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=subscription-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60
    networks:
      - app-tier
  rabbitmq:
    image: rabbitmq:management
    mem_limit: 512m
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 2s
      retries: 60
    networks:
      - app-tier

networks:
  app-tier: 
    name: app-tier
    driver: bridge
