version: "3.8"

services:
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - app-tier
networks:
    app-tier: 
        name: app-tier
        driver: bridge
