version: "3.8"

services:
  mailer:
    image: mailer:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: '256M'
      restart_policy:
        condition: on-failure
    ports:
      - "8083:8083"
    networks:
      - app-tier
networks:
  app-tier: 
    name: app-tier
    driver: bridge
